version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-group-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - 1panel-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  1panel-network:
    external: true